---
- name: Uninstall deprecated packages or ones we don't want anymore
  apt: name={{ item }} state=absent purge=yes
  with_items:
    - phpunit

- name: Install necessary packages for proper system state
  apt: name={{ item }} state=latest
  with_items:
    - build-essential
    - lua5.2
    - liblua5.2-dev
    - postgresql
    - libpq-dev
    - pmake
    - imagemagick
    - exim4
    - python-pip
    
- pip: name=markdown2